# In device_base.yaml
esphome:
  name: ${node_name}
  platform: ESP32
  board: nodemcu-32s
  build_path: ./build/${node_name}

preferences:
  flash_write_interval: 1h

ota:

# I²C Bus
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  frequency: 100kHz

# Enable logging
logger:
  level: ${log_level}

api:
  # encryption:
  #   key: !secret api_encryption_key
  reboot_timeout: 1h


time:
  - platform: homeassistant
    id: homeassistant_time

# Enable Web server
web_server:
  port: 80

captive_portal:

# sensor:
#   - <<: !include common/sensor/uptime.config.yaml
#   - <<: !include common/sensor/wifi_signal.config.yaml
# binary_sensor:
#   - <<: !include common/binary_sensor/connection_status.config.yaml

# switch:
#   - <<: !include common/switch/restart_switch.config.yaml